let handler = async (m, { conn, isAdmin, isOwner, isBotAdmin, reply }) => {
    if (!m.isGroup) return reply('This command only works in groups! ❌');
    if (!(isAdmin || isOwner)) return reply('❌ This command is restricted to Admins or the Owner!');
    if (!isBotAdmin) return reply('❌ I need to be an Admin to generate the invite link.');

    try {
        let code = await conn.groupInviteCode(m.chat);
        let inviteLink = `https://chat.whatsapp.com/${code}`;
        reply(`*🔗 Group Invite Link*\n\n*Link:* ${inviteLink}\n\n_Generated by ${global.botName || 'Bot'}_`);
    } catch (e) {
        reply('🚫 Failed to generate link. Make sure I am an Admin.');
    }
};

handler.help = ['invite'];
handler.tags = ['admin'];
handler.command = /^(invite|link|grouplink)$/i;
handler.group = true;

module.exports = handler;
