let handler = async (m, { conn, isBotAdmin, isAdmin, isOwner }) => {
    if (!m.isGroup) return m.reply('This command only works in groups! ❌');
    if (!(isAdmin || isOwner)) return m.reply('❌ This command is restricted to Admins or the Owner!');
    if (!isBotAdmin) return m.reply('❌ I need to be an Admin to generate the invite link.');

    try {
        // Fetch the group invite code
        let response = await conn.groupInviteCode(m.chat);
        let inviteLink = `https://chat.whatsapp.com/${response}`;

        let caption = `*🔗 Group Invite Link*\n\n` +
                      `*Group:* ${m.metadata.subject}\n` +
                      `*Link:* ${inviteLink}\n\n` +
                      `_Generated by 🕊🦋⃝♥⃝ѕиєнα🍁♥⃝🦋⃝🕊_`;

        await conn.reply(m.chat, caption, m, { detectLinks: true });
    } catch (e) {
        m.reply('🚫 Failed to generate link. Make sure I am an Admin.');
    }
};

handler.help = ['invite'];
handler.tags = ['admin'];
handler.command = /^(invite|link|grouplink)$/i;
handler.group = true;

module.exports = handler;

